
 setwd("~/Documents/wd")



base_args <- c(
  "/opt/conda/lib/R/bin/exec/R"                                                                                                           ,
  "--no-echo"                                                                                                                             ,
  "--no-restore"                                                                                                                          ,
  "--vanilla"                                                                                                                             ,
  "--file=~/Documents/GitHub/strand-seq-graph-phasing/scripts/R/clustering_orient_strandstate.snakemake.R",
  "--args"
)



# HG0071hifiasm -----------------------------------------------------------

args <-
  c(
    base_args,
 "--mem-alignment-bams"                                                                                                                  ,
 "bwa_alignments/mem/HG00171hifiasm.p_utg/000000.mdup.bam"                                                                               ,
 "bwa_alignments/mem/HG00171hifiasm.p_utg/000001.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000002.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000003.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000004.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000005.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000006.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000007.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000008.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000009.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000010.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000011.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000012.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000013.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000014.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000015.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000016.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000017.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000018.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000019.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000020.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000021.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000022.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000023.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000024.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000025.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000026.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000027.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000028.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000029.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000030.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000031.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000032.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000033.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000034.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000035.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000036.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000037.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000038.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000039.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000040.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000041.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000042.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000043.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000044.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000045.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000046.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000047.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000048.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000049.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000050.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000051.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000052.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000053.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000054.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000055.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000056.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000057.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000058.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000059.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000060.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000061.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000062.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000063.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000064.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000065.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000066.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000067.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000068.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000069.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000070.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000071.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000072.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000073.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000074.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000075.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000076.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000077.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000078.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000079.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000080.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000081.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000082.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000083.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000084.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000085.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000086.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000087.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000088.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000089.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000090.mdup.bam"                                                                               ,
"bwa_alignments/mem/HG00171hifiasm.p_utg/000091.mdup.bam"                                                                               ,
 "bwa_alignments/mem/HG00171hifiasm.p_utg/000092.mdup.bam"                                                                               ,
 "bwa_alignments/mem/HG00171hifiasm.p_utg/000093.mdup.bam"                                                                               ,
 "bwa_alignments/mem/HG00171hifiasm.p_utg/000094.mdup.bam"                                                                               ,
 "bwa_alignments/mem/HG00171hifiasm.p_utg/000095.mdup.bam"                                                                               ,
 "--fastmap-alignments"                                                                                                                  ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000000_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000001_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000002_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000003_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000004_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000005_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000006_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000007_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000008_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000009_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000010_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000011_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000012_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000013_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000014_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000015_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000016_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000017_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000018_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000019_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000020_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000021_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000022_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000023_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000024_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000025_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000026_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000027_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000028_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000029_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000030_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000031_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000032_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000033_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000034_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000035_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000036_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000037_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000038_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000039_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000040_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000041_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000042_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000043_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000044_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000045_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000046_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000047_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000048_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000049_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000050_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000051_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000052_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000053_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000054_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000055_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000056_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000057_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000058_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000059_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000060_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000061_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000062_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000063_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000064_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000065_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000066_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000067_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000068_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000069_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000070_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000071_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000072_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000073_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000074_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000075_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000076_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000077_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000078_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000079_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000080_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000081_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000082_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000083_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000084_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000085_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000086_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000087_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000088_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000089_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000090_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000091_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000092_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000093_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000094_maximal_unique_exact_match.tsv"                                                     ,
 "bwa_alignments/fastmap/HG00171hifiasm.p_utg/000095_maximal_unique_exact_match.tsv"                                                     ,
 "--homology"                                                                                                                            ,
 "homology/HG00171hifiasm.p_utg/HG00171hifiasm.p_utg_combined_mashmap_bubblegun_homology.tsv"                                            ,
 "--connected-components"                                                                                                                ,
 "gfa/ccs/HG00171hifiasm.p_utg_exploded_ccs.tsv"                                                                                         ,
 "--segment-length-threshold"                                                                                                            ,
 "250000"                                                                                                                                ,
 "--expect-XY-separate"                                                                                                                  ,
 "False"                                                                                                                                 ,
 "--threads"                                                                                                                             ,
 "10"                                                                                                                                     ,
 "--output"                                                                                                                              ,
 "haplotype_marker_counts/HG00171hifiasm.p_utg_haplotype_marker_counts.csv" 
  )

# Functions ---------------------------------------------------------------


export_clusters_test <- function() {
  cluster_palette <-
    cluster_df %>%
    distinct(cluster) %>%
    mutate(Color = rainbow(n())) %>% 
    mutate(Color = ifelse(is.na(cluster), 'black', Color))
  
  ref <-
    pafr::read_paf(
      'reference_alignments/T2Tv11_hg002Yv2_chm13/NA20355_T2Tv11_hg002Yv2_chm13_ref-aln.paf',
      tibble = TRUE,
      include_tags = FALSE) %>%
    group_by(qname) %>%
    slice_head(n = 1) %>%
    ungroup() %>%
    dplyr::rename(unitig = qname)

  cluster_df %>%
    left_join(cluster_palette, by = 'cluster') %>%
    left_join(homology_df) %>%
    left_join(ref, by='unitig') %>%
    select(unitig, everything()) %>%
    readr::write_csv('test_colors.csv')
  
  invisible(TRUE)
}

