samples: /absolute/path/to/strand-seq-graph-phasing/config/samples.tsv
segmentLengthThreshold: 250000
tangleSegmentLengthThreshold: 250000
per_thread_memory: False

# experimental features
calc_breakpoints: True
